version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/playground-logging/unanimous
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu