# logging-deploy.yml

name: logging-system

on:
  workflow_dispatch:

env: 
  S3_BUCKET_NAME: logging-system-deploy
  PROJECT_NAME: playground-logging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./unanimousbacks
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./unanimousbacks
        shell: bash
          
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ImageCodeDeployAccessKey }}
          aws-secret-access-key: ${{ secrets.ImageCodeDeploySecretKey }}
          aws-region: ${{ secrets.ImageCodeDeployRegion }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

        
